version: "3"
services:
        db:
                image: postgres:12.7
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=secret
                        - POSTGRES_DB=postgres
                ports:
                        - "5432:5432"
                volumes:
                        - pgdata:/var/lib/postgresql/data
volumes: 
        pgdata:
